name: Latest blog posts workflow
on:
  schedule:  # Run workflow automatically
    - cron: '* 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in nlamprian.me posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 5
          feed_list: "https://nlamprian.me/feed"
